{
 "title": "Golang",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Prometheus job",
    "query": {
     "query": "label_values(go_gc_cycles_automatic_gc_cycles_total,$job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_durations_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "duration settings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_durations_seconds[$__rate_interval]) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(go_cpu_classes_user_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(go_cpu_classes_total_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}