{
 "title": "Tarantool 3 dashboard",
 "description": "Dashboard for Tarantool 3 application and database server monitoring, based on grafonnet library.",
 "tags": [ "tarantool" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Prometheus job",
    "query": "label_values(tnt_info_uptime,job)"
   },
   {
    "name": "alias",
    "label": "Instances",
    "query": "label_values(tnt_info_uptime{job=~\"$job\"},alias)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster status overview",
     "type": "table",
     "description": "Overview of Tarantool instances observed by Prometheus job.\n\nIf instance row is *red*, it means Prometheus can't reach\nURI specified in targets or ran into error.\nIf instance row is *green*, it means instance is up and running and\nPrometheus is successfully extracting metrics from it.\n\"Uptime\" column shows time since instant start.\n\nInstance alias filtering is disabled here.\n\nIf Prometheus job filter is not specified, displays running instances\nand ignores unreachable instances (we have no specific source to fetch).\n\nColor scheme is expected to work properly only for Grafana 11+.\n\nThis panel is designed to work with Prometheus client\nset up to have each Tarantool instance as a separate pull target.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "up{job=~\"$job\"} * on(instance) group_left(alias) tnt_info_uptime{job=~\"$job\"} or\non(instance) label_replace(up{job=~\"$job\"}, \"alias\", \"Not available\", \"instance\", \".*\")\n"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Count of running Tarantool instances observed by Prometheus job.\nIf Prometheus can't reach URI specified in targets\nor ran into error, instance is not counted.\n\nInstance alias filtering is disabled here.\n\nThis panel is designed to work with Prometheus client\nset up to have each Tarantool instance as a separate pull target.\n",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(up{job=~\"$job\"})"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Overall value of memory used by Tarantool\nitems and indexes (*arena_used* value).\nIf Tarantool instance is not available\nfor Prometheus metrics extraction now,\nits contribution is not counted.\n\nInstance alias filtering is disabled here.\n",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
     "targets": [
      {
       "expr": "sum(tnt_slab_arena_used{job=~\"$job\"})"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Overall value of memory available for Tarantool items\nand indexes allocation (*memtx_memory* or *quota_size* values).\nIf Tarantool instance is not available for Prometheus metrics\nextraction now, its contribution is not counted.\n\nInstance alias filtering is disabled here.\n",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "targets": [
      {
       "expr": "sum(tnt_slab_quota_size{job=~\"$job\"})"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Overall rate of HTTP requests processed\non Tarantool instances (all methods and response codes).\nIf Tarantool instance is not available for Prometheus metrics\nextraction now, its contribution is not counted.\n\nInstance alias filtering is disabled here.\n",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_latency_count{job=~\"$job\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Overall rate of network requests processed on Tarantool instances.\nIf Tarantool instance is not available for Prometheus metrics\nextraction now, its contribution is not counted.\n\nInstance alias filtering is disabled here.\n",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(tnt_net_requests_total{job=~\"$job\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Overall rate of operations performed on Tarantool spaces\n(*select*, *insert*, *update* etc.).\nIf Tarantool instance is not available for Prometheus metrics\nextraction now, its contribution is not counted.\n\nInstance alias filtering is disabled here.\n",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(tnt_stats_op_total{job=~\"$job\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Tarantool configuration status",
     "type": "timeseries",
     "description": "Current Tarantool 3 configuration apply status for a cluster instance.\n`uninitialized` decribes uninitialized instance,\n`check_errors` decribes instance with at least one apply error,\n`check_warnings` decribes instance with at least one apply warning,\n`startup_in_progress` decribes instance doing initial configuration apply,\n`reload_in_progress` decribes instance doing configuration apply over existing configuration,\n`ready` describes a healthy instance.\n\nPanel minimal requirements: Grafana 8.\n\nPanel minimal requirements: metrics 1.2.0, Tarantool 3.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "1 * tnt_config_status{alias=~\"$alias\",job=~\"$job\",status=\"uninitialized\"} + on(alias)\n2 * tnt_config_status{alias=~\"$alias\",job=~\"$job\",status=\"check_errors\"} + on(alias)\n3 * tnt_config_status{alias=~\"$alias\",job=~\"$job\",status=\"startup_in_progress\"} + on(alias)\n4 * tnt_config_status{alias=~\"$alias\",job=~\"$job\",status=\"reload_in_progress\"} + on(alias)\n5 * tnt_config_status{alias=~\"$alias\",job=~\"$job\",status=\"check_warnings\"} + on(alias)\n6 * tnt_config_status{alias=~\"$alias\",job=~\"$job\",status=\"ready\"}\n",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Tarantool configuration warnings",
     "type": "timeseries",
     "description": "Number of \"warn\" alerts on Tarantool 3 configuration apply on a cluster instance.\n\"warn\" alerts cover non-critical issues which do not result in apply failure,\nlike missing a role to grant for a user.\n\nPanel minimal requirements: metrics 1.2.0, Tarantool 3.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "tnt_config_alerts{alias=~\"$alias\",job=~\"$job\",level=\"warn\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Tarantool configuration errors",
     "type": "timeseries",
     "description": "Number of \"error\" alerts on Tarantool 3 configuration apply on a cluster instance.\n\"error\" alerts cover critical issues which results in apply failure,\nlike instance missing itself in configuration.\n\nPanel minimal requirements: metrics 1.2.0, Tarantool 3.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "targets": [
      {
       "expr": "tnt_config_alerts{alias=~\"$alias\",job=~\"$job\",level=\"error\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Tarantool instance status",
     "type": "timeseries",
     "description": "`master` status means instance is available for read and\nwrite operations. `replica` status means instance is\navailable only for read operations.\n\nPanel minimal requirements: metrics 0.11.0, Grafana 8.\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "tnt_read_only{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Instance election state",
     "type": "timeseries",
     "description": "Election state (mode) of the node.\nWhen election is enabled, the node is writable only in the leader state.\n\nAll the non-leader nodes are called `follower`s.\n`candidate`s are nodes that start a new election round.\n`leader` is a node that collected a quorum of votes.\n\nPanel minimal requirements: Grafana 8.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.1.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "tnt_election_state{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Instance election vote",
     "type": "timeseries",
     "description": "ID of a node the current node votes for.\nIf the value is 0, it means the node hasn’t\nvoted in the current term yet.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.1.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
     "targets": [
      {
       "expr": "tnt_election_vote{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Instance election leader",
     "type": "timeseries",
     "description": "Leader node ID in the current term.\nIf the value is 0, it means the node doesn’t know which\nnode is the leader in the current term.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.1.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "tnt_election_leader{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Election term",
     "type": "timeseries",
     "description": "Current election term.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.1.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
     "targets": [
      {
       "expr": "tnt_election_term{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tarantool replication status",
     "type": "timeseries",
     "description": "`follows` status means replication is running.\nOtherwise, `not running` is displayed.\n\nPanel minimal requirements: metrics 0.13.0, Grafana 8.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "tnt_replication_status{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}} {{stream}} ({{id}})"
      }
     ]
    },
    {
     "title": "Tarantool replication lag",
     "type": "timeseries",
     "description": "Replication lag value for Tarantool instance.\n\nPanel minimal requirements: metrics 0.13.0.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "tnt_replication_lag{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}} ({{id}})"
      }
     ]
    },
    {
     "title": "Synchronous queue owner",
     "type": "timeseries",
     "description": "Instance ID of the current synchronous replication master.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.8.1.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "tnt_synchro_queue_owner{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Synchronous queue term",
     "type": "timeseries",
     "description": "Current queue term.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.8.1.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
     "targets": [
      {
       "expr": "tnt_synchro_queue_term{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Synchronous queue transactions",
     "type": "timeseries",
     "description": "Count of transactions collecting confirmations now.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.8.1.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "tnt_synchro_queue_len{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Synchronous queue busy",
     "type": "timeseries",
     "description": "Whether the queue is processing any system entry (CONFIRM/ROLLBACK/PROMOTE/DEMOTE).\n\nPanel minimal requirements: Grafana 8.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.8.1.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
     "targets": [
      {
       "expr": "tnt_synchro_queue_busy{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool HTTP statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success requests (code 2xx)",
     "type": "timeseries",
     "description": "Requests, processed with success (code 2xx) on Tarantool's side.\nGraph shows mean count per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(http_server_request_latency_count{alias=~\"$alias\",job=~\"$job\",status=~\"^2\\\\d{2}$\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Error requests (code 4xx)",
     "type": "timeseries",
     "description": "Requests, processed with 4xx error on Tarantool's side.\nGraph shows mean count per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "targets": [
      {
       "expr": "rate(http_server_request_latency_count{alias=~\"$alias\",job=~\"$job\",status=~\"^4\\\\d{2}$\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Error requests (code 5xx)",
     "type": "timeseries",
     "description": "Requests, processed with 5xx error on Tarantool's side.\nGraph shows mean count per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "targets": [
      {
       "expr": "rate(http_server_request_latency_count{alias=~\"$alias\",job=~\"$job\",status=~\"^5\\\\d{2}$\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Success requests latency (code 2xx)",
     "type": "timeseries",
     "description": "99th percentile of requests latency.\nIncludes only requests processed with success\n(code 2xx) on Tarantool's side.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "http_server_request_latency{alias=~\"$alias\",job=~\"$job\",quantile=\"0.99\",status=~\"^2\\\\d{2}$\"}",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Error requests latency (code 4xx)",
     "type": "timeseries",
     "description": "99th percentile of requests latency.\nIncludes only requests processed with\n4xx error on Tarantool's side.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "targets": [
      {
       "expr": "http_server_request_latency{alias=~\"$alias\",job=~\"$job\",quantile=\"0.99\",status=~\"^4\\\\d{2}$\"}",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    },
    {
     "title": "Error requests latency (code 5xx)",
     "type": "timeseries",
     "description": "99th percentile of requests latency.\nIncludes only requests processed with\n5xx error on Tarantool's side.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "targets": [
      {
       "expr": "http_server_request_latency{alias=~\"$alias\",job=~\"$job\",quantile=\"0.99\",status=~\"^5\\\\d{2}$\"}",
       "legendFormat": "{{alias}} — {{method}} {{path}} (code {{status}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool network activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Net memory",
     "type": "timeseries",
     "description": "Memory used for network input/output buffers.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "tnt_info_memory_net{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Data received",
     "type": "timeseries",
     "description": "Data received by instance from binary protocol connections.\nGraph shows average bytes per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
     "targets": [
      {
       "expr": "rate(tnt_net_received_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Data sent",
     "type": "timeseries",
     "description": "Data sent by instance with binary protocol connections.\nGraph shows average bytes per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
     "targets": [
      {
       "expr": "rate(tnt_net_sent_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Network requests handled",
     "type": "timeseries",
     "description": "Number of network requests this instance has handled.\nGraph shows mean rps.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "rate(tnt_net_requests_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Network requests pending",
     "type": "timeseries",
     "description": "Number of pending network requests.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "tnt_net_requests_current{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Processed requests",
     "type": "timeseries",
     "description": "Average number of requests processed by tx thread per second.\n\nPanel minimal requirements: metrics 0.13.0, Tarantool 2.10-beta2.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "rate(tnt_net_requests_in_progress_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Requests in progress",
     "type": "timeseries",
     "description": "Number of requests currently being processed in the tx thread.\n\nPanel minimal requirements: metrics 0.13.0, Tarantool 2.10-beta2.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 84 },
     "targets": [
      {
       "expr": "tnt_net_requests_in_progress_current{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Requests in queue (overall)",
     "type": "timeseries",
     "description": "Average number of requests which was placed in queues\nof streams per second.\n\nPanel minimal requirements: metrics 0.13.0, Tarantool 2.10-beta2.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "rate(tnt_net_requests_in_stream_queue_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Requests in queue (current)",
     "type": "timeseries",
     "description": "Number of requests currently waiting in queues of streams.\n\nPanel minimal requirements: metrics 0.13.0, Tarantool 2.10-beta2.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 84 },
     "targets": [
      {
       "expr": "tnt_net_requests_in_stream_queue_current{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "New binary connections",
     "type": "timeseries",
     "description": "Average number of new binary protocol connections per second.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "rate(tnt_net_connections_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Current binary connections",
     "type": "timeseries",
     "description": "Number of current active binary protocol connections.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "targets": [
      {
       "expr": "tnt_net_connections_current{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Data sent (per thread)",
     "type": "timeseries",
     "description": "Data sent by instance with binary protocol connections,\nseparated per thread.\nGraph shows average bytes per second.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_sent_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Data received (per thread)",
     "type": "timeseries",
     "description": "Data received by instance from binary protocol connections,\nseparated per thread.\nGraph shows average bytes per second.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_received_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "New binary connections (per thread)",
     "type": "timeseries",
     "description": "Average number of new binary protocol connections per second,\nseparated per thread.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_connections_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Current binary connections (per thread)",
     "type": "timeseries",
     "description": "Number of current active binary protocol connections,\nseparated per thread.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "expr": "tnt_net_per_thread_connections_current{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Network requests handled (per thread)",
     "type": "timeseries",
     "description": "Number of network requests this instance has handled,\nseparated per thread.\nGraph shows mean rps.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_requests_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Processed requests (per thread)",
     "type": "timeseries",
     "description": "Average number of requests processed per second,\nseparated per thread.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 116 },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_requests_in_progress_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Requests in queue (overall per thread)",
     "type": "timeseries",
     "description": "Average number of requests which was placed in queues\nof streams per second, separated per thread.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 116 },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_requests_in_stream_queue_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Network requests pending (per thread)",
     "type": "timeseries",
     "description": "Number of pending network requests,\nseparated per thread.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
     "targets": [
      {
       "expr": "tnt_net_per_thread_requests_current{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Requests in progress (per thread)",
     "type": "timeseries",
     "description": "Number of requests currently being processed,\nseparated per thread.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
     "targets": [
      {
       "expr": "tnt_net_per_thread_requests_in_progress_current{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Requests in queue (current per thread)",
     "type": "timeseries",
     "description": "Number of requests currently waiting in queues of streams,\nseparated per thread.\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
     "targets": [
      {
       "expr": "tnt_net_per_thread_requests_in_stream_queue_current{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}} (thread {{thread}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool memtx allocation overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slab allocator monitoring information",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 133 }
    },
    {
     "title": "Used by slab allocator (quota_used_ratio)",
     "type": "timeseries",
     "description": "`quota_used_ratio` = `quota_used` / `quota_size`.\n\n`quota_used` – used by slab allocator (for both tuple and index slabs).\n\n`quota_size` – memory limit for slab allocator (as configured in the *memtx_memory* parameter).\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
     "targets": [
      {
       "expr": "tnt_slab_quota_used_ratio{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used for tuples and indexes (arena_used_ratio)",
     "type": "timeseries",
     "description": "`arena_used_ratio` = `arena_used` / `arena_size`.\n\n`arena_used` – used for both tuples and indexes.\n\n`arena_size` – allocated for both tuples and indexes.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
     "targets": [
      {
       "expr": "tnt_slab_arena_used_ratio{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used for tuples (items_used_ratio)",
     "type": "timeseries",
     "description": "`items_used_ratio` = `items_used` / `items_size`.\n\n`items_used` – used only for tuples.\n\n`items_size` – allocated only for tuples.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
     "targets": [
      {
       "expr": "tnt_slab_items_used_ratio{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used by slab allocator (quota_used)",
     "type": "timeseries",
     "description": "Memory used by slab allocator (for both tuple and index slabs).\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "tnt_slab_quota_used{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used for tuples and indexes (arena_used)",
     "type": "timeseries",
     "description": "Memory used for both tuples and indexes.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 144 },
     "targets": [
      {
       "expr": "tnt_slab_arena_used{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Used for tuples (items_used)",
     "type": "timeseries",
     "description": "Memory used for only tuples.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 144 },
     "targets": [
      {
       "expr": "tnt_slab_items_used{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Slab allocator memory limit (quota_size)",
     "type": "timeseries",
     "description": "Memory limit for slab allocator (as configured in the *memtx_memory* parameter).\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 152 },
     "targets": [
      {
       "expr": "tnt_slab_quota_size{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Allocated for tuples and indexes (arena_size)",
     "type": "timeseries",
     "description": "Memory allocated for both tuples and indexes by slab allocator.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 152 },
     "targets": [
      {
       "expr": "tnt_slab_arena_size{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Allocated for tuples (items_size)",
     "type": "timeseries",
     "description": "Memory allocated for only tuples by slab allocator.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 152 },
     "targets": [
      {
       "expr": "tnt_slab_items_size{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool MVCC overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction statements size (total)",
     "type": "timeseries",
     "description": "Each operation like `space:replace{}` turns into ``statement``\nfor the current transaction.\n\nGraph shows the number of bytes that are allocated\nfor the statements of all current transactions.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_statements{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction statements size (average)",
     "type": "timeseries",
     "description": "Each operation like `space:replace{}` turns into ``statement``\nfor the current transaction.\n\nGraph shows average bytes used by transactions for statements\n(`txn.statements.total` bytes / number of open transactions).\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 161 },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_statements{alias=~\"$alias\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction statements size (max)",
     "type": "timeseries",
     "description": "Each operation like `space:replace{}` turns into ``statement``\nfor the current transaction.\n\nGraph shows the maximum number of bytes used by one\nthe current transaction for statements.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 161 },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_statements{alias=~\"$alias\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction user size (total)",
     "type": "timeseries",
     "description": "User may allocate memory for the current transaction with\nTarantool C APIfunction `box_txn_alloc()`.\n\nGraph shows memory allocated for all current transactions.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 169 },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_user{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction user size (average)",
     "type": "timeseries",
     "description": "User may allocate memory for the current transaction with\nTarantool C APIfunction `box_txn_alloc()`.\n\nGraph shows transaction average\n(total allocated bytes / number of all current transactions).\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 169 },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_user{alias=~\"$alias\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction user size (max)",
     "type": "timeseries",
     "description": "User may allocate memory for the current transaction with\nTarantool C APIfunction `box_txn_alloc()`.\n\nGraph shows the maximum number of bytes allocated over all current transactions.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 169 },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_user{alias=~\"$alias\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction system size (total)",
     "type": "timeseries",
     "description": "System may store utility things like logs and savepoints\nfor each transaction.\n\nGraph shows memory allocated for all current transactions.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 177 },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_system{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction system size (average)",
     "type": "timeseries",
     "description": "System may store utility things like logs and savepoints\nfor each transaction.\n\nGraph shows transaction average\n(total allocated bytes / number of all current transactions).\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 177 },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_system{alias=~\"$alias\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction system size (max)",
     "type": "timeseries",
     "description": "System may store utility things like logs and savepoints\nfor each transaction.\n\nGraph shows the maximum number of bytes allocated over all current transactions.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 177 },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_system{alias=~\"$alias\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Trackers size (total)",
     "type": "timeseries",
     "description": "Tarantool allocates memory for trackers\nthat keep track of transaction reads.\n\nGraph shows memory allocated for trackers of all current transactions.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 185 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_trackers{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Trackers size (average)",
     "type": "timeseries",
     "description": "Tarantool allocates memory for trackers\nthat keep track of transaction reads.\n\nGraph shows transaction tracker average\n(total allocated bytes / number of all current transactions).\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 185 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_trackers{alias=~\"$alias\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Trackers size (max)",
     "type": "timeseries",
     "description": "Tarantool allocates memory for trackers\nthat keep track of transaction reads.\n\nGraph shows the maximum number of bytes allocated for a tracker\nover all current transactions.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 185 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_trackers{alias=~\"$alias\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Conflicts size (total)",
     "type": "timeseries",
     "description": "Tarantool allocates memory in case of conflicts.\n\nGraph shows memory allocated for all current conflicts.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 193 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_conflicts{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Conflicts size (average)",
     "type": "timeseries",
     "description": "Tarantool allocates memory in case of conflicts.\n\nGraph shows transaction conflict average\n(total allocated bytes / number of all current conflict).\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 193 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_conflicts{alias=~\"$alias\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Conflicts size (max)",
     "type": "timeseries",
     "description": "Tarantool allocates memory in case of conflicts.\n\nGraph shows the maximum number of bytes allocated for a transaction conflict.\n\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 193 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_conflicts{alias=~\"$alias\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Stories tuples used",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are used by active read-write transactions.\n\nGraph shows the number of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 201 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_used_stories{alias=~\"$alias\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Stories tuples used size",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are used by active read-write transactions.\n\nGraph shows total size of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 201 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_used_stories{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Retained tuples used",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are used by active read-write transactions.\n\nGraph shows the number of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 201 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_used_retained{alias=~\"$alias\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Retained tuples used size",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are used by active read-write transactions.\n\nGraph shows total size of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 201 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_used_retained{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Stories tuples in read views",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are used by read-only transactions (i.e. in read view).\n\nGraph shows the number of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 209 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_read_view_stories{alias=~\"$alias\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Stories tuples in read views size",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are used by read-only transactions (i.e. in read view).\n\nGraph shows total size of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 209 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_read_view_stories{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Retained tuples in read views",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are used by read-only transactions (i.e. in read view).\n\nGraph shows the number of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 209 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_read_view_retained{alias=~\"$alias\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Retained tuples in read views size",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are used by read-only transactions (i.e. in read view).\n\nGraph shows total size of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 209 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_read_view_retained{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Stories tuples tracked",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are not used by current transactions,\nbut are used by MVCC to track reads.\n\nGraph shows the number of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 217 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_tracking_stories{alias=~\"$alias\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Stories tuples tracked size",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are not used by current transactions,\nbut are used by MVCC to track reads.\n\nGraph shows total size of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 217 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_tracking_stories{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Retained tuples tracked",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are not used by current transactions,\nbut are used by MVCC to track reads.\n\nGraph shows the number of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 217 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_tracking_retained{alias=~\"$alias\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Retained tuples tracked size",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are not used by current transactions,\nbut are used by MVCC to track reads.\n\nGraph shows total size of tuples.\nPanel minimal requirements: metrics 0.15.1, Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 217 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_tracking_retained{alias=~\"$alias\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool space statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of records (memtx)",
     "type": "timeseries",
     "description": "Number of records in the space (memtx engine).\nName of space is specified after dash.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
     "targets": [
      {
       "expr": "tnt_space_len{alias=~\"$alias\",engine=\"memtx\",job=~\"$job\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "Number of records (vinyl)",
     "type": "timeseries",
     "description": "Number of records in the space (vinyl engine).\nName of space is specified after dash.\nBy default this metrics is disabled,\nto enable it you must set global variable\ninclude_vinyl_count to true. Beware that\ncount() operation scans the space and may\nslow down your app.\n\nPanel minimal requirements: metrics 0.13.0.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
     "targets": [
      {
       "expr": "tnt_vinyl_tuples{alias=~\"$alias\",engine=\"vinyl\",job=~\"$job\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "Data size (memtx)",
     "type": "timeseries",
     "description": "Total number of bytes in all tuples of the space (memtx engine).\nName of space is specified after dash.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 234 },
     "targets": [
      {
       "expr": "tnt_space_bsize{alias=~\"$alias\",engine=\"memtx\",job=~\"$job\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "Index size",
     "type": "timeseries",
     "description": "Total number of bytes taken by the index.\nName of space is specified after dash,\nindex name specified in parentheses.\nIncludes both memtx and vinyl spaces.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 234 },
     "targets": [
      {
       "expr": "tnt_space_index_bsize{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}} — {{name}} ({{index_name}})"
      }
     ]
    },
    {
     "title": "Total size (memtx)",
     "type": "timeseries",
     "description": "Total size of tuples and all indexes in the space (memtx engine).\nName of space is specified after dash.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 234 },
     "targets": [
      {
       "expr": "tnt_space_total_bsize{alias=~\"$alias\",engine=\"memtx\",job=~\"$job\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool vinyl statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vinyl disk data",
     "type": "timeseries",
     "description": "The amount of data stored in the `.run` files located in the `vinyl_dir` directory.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
     "targets": [
      {
       "expr": "tnt_vinyl_disk_data_size{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl disk index",
     "type": "timeseries",
     "description": "The amount of data stored in the `.index` files located in the `vinyl_dir` directory.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 243 },
     "targets": [
      {
       "expr": "tnt_vinyl_disk_index_size{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Tuples cache memory",
     "type": "timeseries",
     "description": "Amount of memory in bytes currently used to store tuples (data).\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 251 },
     "targets": [
      {
       "expr": "tnt_vinyl_memory_tuple_cache{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Index memory",
     "type": "timeseries",
     "description": "Amount of memory in bytes currently used to store indexes.\nIf the metric value is close to box.cfg.vinyl_memory, this\nindicates that vinyl_page_size was chosen incorrectly.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 251 },
     "targets": [
      {
       "expr": "tnt_vinyl_memory_page_index{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Bloom filter memory",
     "type": "timeseries",
     "description": "Amount of memory in bytes used by bloom filters.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 251 },
     "targets": [
      {
       "expr": "tnt_vinyl_memory_bloom_filter{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator dump bandwidth",
     "type": "timeseries",
     "description": "The estimated average rate of taking dumps, bytes per second.\nInitially, the rate value is 10 megabytes per second\nand being recalculated depending on the the actual rate.\nOnly significant dumps that are larger than one megabyte\nare used for the estimate.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 259 },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_dump_bandwidth{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator write rate",
     "type": "timeseries",
     "description": "The actual average rate of performing the write operations, bytes per second.\nThe rate is calculated as a 5-second moving average.\nIf the metric value is gradually going down, this can indicate some disk issues.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 259 },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_write_rate{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator rate limit",
     "type": "timeseries",
     "description": "The write rate limit, bytes per second.\nThe regulator imposes the limit on transactions based on the observed dump/compaction performance.\nIf the metric value is down to approximately 100 Kbps,\nthis indicates issues with the disk or the scheduler.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 259 },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_rate_limit{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Level 0 memory",
     "type": "timeseries",
     "description": "«Level 0» (L0) memory area in bytes. L0 is the area that\nvinyl can use for in-memory storage of an LSM tree.\nBy monitoring this metric, you can see when L0 is getting\nclose to its maximum (tnt_vinyl_regulator_dump_watermark),\nat which time a dump will occur. You can expect L0 = 0\nimmediately after the dump operation is completed.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 267 },
     "targets": [
      {
       "expr": "tnt_vinyl_memory_level0{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator dump watermark",
     "type": "timeseries",
     "description": "The maximum amount of memory used for in-memory storing of a vinyl LSM tree.\nWhen accessing this maximum, the dumping must occur.\nFor details, see https://www.tarantool.io/en/doc/latest/book/box/engines/#engines-algorithm-filling-lsm.\nThe value is slightly smaller than the amount of memory allocated for vinyl trees,\nwhich is the `vinyl_memory` parameter.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 267 },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_dump_watermark{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator blocked writers",
     "type": "timeseries",
     "description": "The number of fibers that are blocked waiting for Vinyl level0 memory quota.\n\nPanel minimal requirements: metrics 0.13.0, Tarantool 2.8.3.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 267 },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_blocked_writers{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl tx commit rate",
     "type": "timeseries",
     "description": "Average per second rate of commits (successful transaction ends).\nIt includes implicit commits: for example, any insert operation causes a commit\nunless it is within a `box.begin()`–`box.commit()` block.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 275 },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_tx_commit{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl tx rollback rate",
     "type": "timeseries",
     "description": "Average per second rate of rollbacks (unsuccessful transaction ends).\nThis is not merely a count of explicit `box.rollback()` requests — it includes requests\nthat ended with errors.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 275 },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_tx_rollback{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl tx conflict rate",
     "type": "timeseries",
     "description": "Average per second rate of conflicts that caused transactions to roll back.\nThe ratio `tx conflicts` / `tx commits` above 5% indicates that vinyl is not healthy.\nAt this moment you’ll probably see a lot of other problems with vinyl.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 275 },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_tx_conflict{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl read views",
     "type": "timeseries",
     "description": "Number of current read views, that is, transactions entered a read-only state\nto avoid conflict temporarily.\nIf the value stays non-zero for a long time, it indicates of a memory leak.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 275 },
     "targets": [
      {
       "expr": "tnt_vinyl_tx_read_views{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler tasks in progress",
     "type": "timeseries",
     "description": "The number of the scheduler dump/compaction tasks in progress now.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 283 },
     "targets": [
      {
       "expr": "tnt_vinyl_scheduler_tasks{alias=~\"$alias\",job=~\"$job\",status=\"inprogress\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler failed tasks rate",
     "type": "timeseries",
     "description": "Scheduler dump/compaction tasks failed.\nAverage per second rate is shown.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 283 },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_scheduler_tasks{alias=~\"$alias\",job=~\"$job\",status=\"failed\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler dump time rate",
     "type": "timeseries",
     "description": "Time spent by all worker threads performing dumps.\nAverage per second rate is shown.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 283 },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_scheduler_dump_time{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler dump count rate",
     "type": "timeseries",
     "description": "Scheduler dumps completed average per second rate.\n\nPanel minimal requirements: metrics 0.13.0.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 283 },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_scheduler_dump_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool CPU statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU user time",
     "type": "timeseries",
     "description": "This is the average share of time\nspent by instance process executing in user mode.\nMetrics obtained using `getrusage()` call.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 292 },
     "targets": [
      {
       "expr": "rate(tnt_cpu_user_time{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "CPU system time",
     "type": "timeseries",
     "description": "This is the average share of time\nspent by instance process executing in kernel mode.\nMetrics obtained using `getrusage()` call.\n\nPanel minimal requirements: metrics 0.8.0.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 292 },
     "targets": [
      {
       "expr": "rate(tnt_cpu_system_time{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool runtime overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lua memory",
     "type": "timeseries",
     "description": "Memory used for objects allocated with Lua\nby using its internal mechanisms.\nLua memory is bounded by 2 GB per instance. \n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 301 },
     "targets": [
      {
       "expr": "tnt_info_memory_lua{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Runtime arena memory",
     "type": "timeseries",
     "description": "Memory used by runtime arena.\nRuntime arena stores network buffers, tuples\ncreated with box.tuple.new and other objects\nallocated by application not covered by basic\nLua mechanisms (spaces data and indexes\nare not included here, see memtx/vinyl arena).\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 301 },
     "targets": [
      {
       "expr": "tnt_runtime_used{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transactions memory",
     "type": "timeseries",
     "description": "Memory in use by active transactions.\nFor the vinyl storage engine, this is the total size of\nall allocated objects (struct txv, struct vy_tx, struct vy_read_interval)\nand tuples pinned for those objects. \n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 301 },
     "targets": [
      {
       "expr": "tnt_info_memory_tx{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Fiber context switches",
     "type": "timeseries",
     "description": "Number of fiber context switches.\nContext switches are counted over all current fibers.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 309 },
     "targets": [
      {
       "expr": "tnt_fiber_csw{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Event loop time",
     "type": "timeseries",
     "description": "Duration of last event loop iteration (tx thread).\nHigh duration results in longer responses,\npossible bad health signals and may be the\nreason of \"Too long WAL write\" errors.\n\nPanel minimal requirements: metrics 0.13.0.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 309 },
     "targets": [
      {
       "expr": "tnt_ev_loop_time{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Number of fibers",
     "type": "timeseries",
     "description": "Current number of fibers in tx thread.\n\nPanel minimal requirements: metrics 0.13.0.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 317 },
     "targets": [
      {
       "expr": "tnt_fiber_amount{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Memory used by fibers",
     "type": "timeseries",
     "description": "Amount of memory used by current fibers.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 317 },
     "targets": [
      {
       "expr": "tnt_fiber_memused{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Memory reserved for fibers",
     "type": "timeseries",
     "description": "Amount of memory reserved for current fibers.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 317 },
     "targets": [
      {
       "expr": "tnt_fiber_memalloc{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool LuaJit statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snap restores",
     "type": "timeseries",
     "description": "Average number of snap restores (guard assertions\nleading to stopping trace executions) per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 326 },
     "targets": [
      {
       "expr": "rate(lj_jit_snap_restore_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "JIT traces written",
     "type": "timeseries",
     "description": "Average number of new JIT traces per second.\n\n\nPanel minimal requirements: metrics 0.6.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 326 },
     "targets": [
      {
       "expr": "rate(lj_jit_trace_num{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "JIT traces aborted",
     "type": "timeseries",
     "description": "Average number of JIT trace aborts per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 326 },
     "targets": [
      {
       "expr": "rate(lj_jit_trace_abort_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Machine code areas",
     "type": "timeseries",
     "description": "Total size of allocated machine code areas.\n\n\nPanel minimal requirements: metrics 0.6.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 326 },
     "targets": [
      {
       "expr": "lj_jit_mcode_size{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Strings interned",
     "type": "timeseries",
     "description": "Average number of strings being extracted from hash instead of allocating per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 334 },
     "targets": [
      {
       "expr": "rate(lj_strhash_hit_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Strings allocated",
     "type": "timeseries",
     "description": "Average number of strings being allocated due to hash miss per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 334 },
     "targets": [
      {
       "expr": "rate(lj_strhash_miss_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "GC steps (atomic)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (atomic state) per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 342 },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_atomic_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "GC steps (sweepstring)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (sweepstring state) per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 342 },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_sweepstring_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "GC steps (finalize)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (finalize state) per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 342 },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_finalize_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "GC steps (sweep)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (sweep state) per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 350 },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_sweep_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "GC steps (propagate)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (propagate state) per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 350 },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_propagate_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "GC steps (pause)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (pause state) per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 350 },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_pause_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "String objects allocated",
     "type": "timeseries",
     "description": "Number of allocated string objects.\n\n\nPanel minimal requirements: metrics 0.6.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 358 },
     "targets": [
      {
       "expr": "lj_gc_strnum{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Table objects allocated",
     "type": "timeseries",
     "description": "Number of allocated table objects.\n\n\nPanel minimal requirements: metrics 0.6.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 358 },
     "targets": [
      {
       "expr": "lj_gc_tabnum{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "cdata objects allocated",
     "type": "timeseries",
     "description": "Number of allocated cdata objects.\n\n\nPanel minimal requirements: metrics 0.6.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 358 },
     "targets": [
      {
       "expr": "lj_gc_cdatanum{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "userdata objects allocated",
     "type": "timeseries",
     "description": "Number of allocated userdata objects.\n\n\nPanel minimal requirements: metrics 0.6.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 358 },
     "targets": [
      {
       "expr": "lj_gc_udatanum{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Current Lua memory",
     "type": "timeseries",
     "description": "Current allocated Lua memory.\n\n\nPanel minimal requirements: metrics 0.6.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 366 },
     "targets": [
      {
       "expr": "lj_gc_memory{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Freed Lua memory",
     "type": "timeseries",
     "description": "Average amount of freed Lua memory per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 366 },
     "targets": [
      {
       "expr": "rate(lj_gc_freed_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Allocated Lua memory",
     "type": "timeseries",
     "description": "Average amount of allocated Lua memory per second.\n\n\nPanel minimal requirements: metrics 0.15.0, Tarantool 2.6.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 366 },
     "targets": [
      {
       "expr": "rate(lj_gc_allocated_total{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tarantool operations statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "SELECT space requests",
     "type": "timeseries",
     "description": "Total count of SELECT requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 375 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"select\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "INSERT space requests",
     "type": "timeseries",
     "description": "Total count of INSERT requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 375 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"insert\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "REPLACE space requests",
     "type": "timeseries",
     "description": "Total count of REPLACE requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 375 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"replace\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "UPSERT space requests",
     "type": "timeseries",
     "description": "Total count of UPSERT requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 383 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"upsert\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "UPDATE space requests",
     "type": "timeseries",
     "description": "Total count of UPDATE requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 383 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"update\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "DELETE space requests",
     "type": "timeseries",
     "description": "Total count of DELETE requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 383 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"delete\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Call requests",
     "type": "timeseries",
     "description": "Requests to execute stored procedures.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 391 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"call\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Eval calls",
     "type": "timeseries",
     "description": "Calls to evaluate Lua code.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 391 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"eval\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Request errors",
     "type": "timeseries",
     "description": "Requests resulted in error.\nGraph shows average errors per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 391 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Authentication requests",
     "type": "timeseries",
     "description": "Authentication requests.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 399 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"auth\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "SQL prepare calls",
     "type": "timeseries",
     "description": "SQL prepare calls.\nGraph shows average calls per second.\n\nPanel minimal requirements: Tarantool 2.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 399 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"prepare\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "SQL execute calls",
     "type": "timeseries",
     "description": "SQL execute calls.\nGraph shows average calls per second.\n\nPanel minimal requirements: Tarantool 2.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 399 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"execute\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction begins",
     "type": "timeseries",
     "description": "Panel displays the count of IPROTO_CALL and\nIPROTO_EVAL operations with `box.begin()`, IPROTO_EXECUTE\noperations with `TRANSACTION START` and IPROTO_BEGIN operations.\nGraph shows average calls per second.\n\nPanel minimal requirements: Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 407 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"begin\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction commits",
     "type": "timeseries",
     "description": "Panel displays the count of IPROTO_CALL and\nIPROTO_EVAL operations with `box.commit()`, IPROTO_EXECUTE\noperations with `COMMIT` and IPROTO_COMMIT operations.\nGraph shows average calls per second.\n\nPanel minimal requirements: Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 407 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"commit\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Transaction rollbacks",
     "type": "timeseries",
     "description": "Panel displays the count of IPROTO_CALL and\nIPROTO_EVAL operations with `box.rollback()`, IPROTO_EXECUTE\noperations with `ROLLBACK` and IPROTO_ROLLBACK operations.\nGraph shows average calls per second.\n\nPanel minimal requirements: Tarantool 2.10.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 407 },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{alias=~\"$alias\",job=~\"$job\",operation=\"rollback\"}[$__rate_interval])",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CRUD module statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "SELECT success requests",
     "type": "timeseries",
     "description": "Total count of success SELECT and PAIRS requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 416 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"select\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "SELECT success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success SELECT and PAIRS CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 416 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"select\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "SELECT error requests",
     "type": "timeseries",
     "description": "Total count of error SELECT and PAIRS requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 416 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"select\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "SELECT error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error SELECT and PAIRS CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 416 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"select\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "SELECT tuples fetched",
     "type": "timeseries",
     "description": "Average number of tuples fetched during SELECT/PAIRS request for a space.\nBoth success and error requests are taken into consideration.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 424 },
     "targets": [
      {
       "expr": "rate(tnt_crud_tuples_fetched{alias=~\"$alias\",job=~\"$job\",operation=\"select\"}[$__rate_interval]) /\n(sum without (status) (rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"select\"}[$__rate_interval])))\n",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "SELECT tuples lookup",
     "type": "timeseries",
     "description": "Average number of tuples looked up on storages while collecting responses\nfor SELECT/PAIRS requests (including scrolls for multibatch requests)\nfor a space. Both success and error requests are taken into consideration.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 424 },
     "targets": [
      {
       "expr": "rate(tnt_crud_tuples_lookup{alias=~\"$alias\",job=~\"$job\",operation=\"select\"}[$__rate_interval]) /\n(sum without (status) (rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"select\"}[$__rate_interval])))\n",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "Map reduce SELECT requests",
     "type": "timeseries",
     "description": "Number of SELECT and PAIRS requests that resulted in map reduce.\nGraph shows average requests per second.\nBoth success and error requests are taken into consideration.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 424 },
     "targets": [
      {
       "expr": "rate(tnt_crud_map_reduces{alias=~\"$alias\",job=~\"$job\",operation=\"select\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "INSERT success requests",
     "type": "timeseries",
     "description": "Total count of success insert and insert_object requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 432 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"insert\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "INSERT success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success insert and insert_object CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 432 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"insert\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "INSERT error requests",
     "type": "timeseries",
     "description": "Total count of error insert and insert_object requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 432 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"insert\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "INSERT error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error insert and insert_object CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 432 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"insert\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "INSERT_MANY success requests",
     "type": "timeseries",
     "description": "Total count of success insert_many and insert_object_many requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 440 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"insert_many\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "INSERT_MANY success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success insert_many and insert_object_many CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 440 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"insert_many\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "INSERT_MANY error requests",
     "type": "timeseries",
     "description": "Total count of error insert_many and insert_object_many requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 440 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"insert_many\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "INSERT_MANY error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error insert_many and insert_object_many CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 440 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"insert_many\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "REPLACE success requests",
     "type": "timeseries",
     "description": "Total count of success replace and replace_object requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 448 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"replace\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "REPLACE success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success replace and replace_object CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 448 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"replace\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "REPLACE error requests",
     "type": "timeseries",
     "description": "Total count of error replace and replace_object requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 448 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"replace\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "REPLACE error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error replace and replace_object CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 448 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"replace\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "REPLACE_MANY success requests",
     "type": "timeseries",
     "description": "Total count of success replace_many and replace_object_many requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 456 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"replace_many\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "REPLACE_MANY success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success replace_many and replace_object_many CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 456 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"replace_many\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "REPLACE_MANY error requests",
     "type": "timeseries",
     "description": "Total count of error replace_many and replace_object_many requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 456 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"replace_many\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "REPLACE_MANY error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error replace_many and replace_object_many CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 456 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"replace_many\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPSERT success requests",
     "type": "timeseries",
     "description": "Total count of success upsert and upsert_object requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 464 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"upsert\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPSERT success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success upsert and upsert_object CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 464 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"upsert\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPSERT error requests",
     "type": "timeseries",
     "description": "Total count of error upsert and upsert_object requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 464 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"upsert\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPSERT error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error upsert and upsert_object CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 464 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"upsert\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPSERT_MANY success requests",
     "type": "timeseries",
     "description": "Total count of success upsert_many and upsert_object_many requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 472 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"upsert_many\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPSERT_MANY success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success upsert_many and upsert_object_many CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 472 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"upsert_many\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPSERT_MANY error requests",
     "type": "timeseries",
     "description": "Total count of error upsert_many and upsert_object_many requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 472 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"upsert_many\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPSERT_MANY error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error upsert_many and upsert_object_many CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 472 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"upsert_many\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPDATE success requests",
     "type": "timeseries",
     "description": "Total count of success update requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 480 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"update\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPDATE success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success update CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 480 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"update\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPDATE error requests",
     "type": "timeseries",
     "description": "Total count of error update requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 480 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"update\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "UPDATE error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error update CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 480 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"update\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "DELETE success requests",
     "type": "timeseries",
     "description": "Total count of success delete requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 488 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"delete\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "DELETE success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success delete CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 488 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"delete\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "DELETE error requests",
     "type": "timeseries",
     "description": "Total count of error delete requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 488 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"delete\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "DELETE error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error delete CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 488 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"delete\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "COUNT success requests",
     "type": "timeseries",
     "description": "Total count of success count requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 496 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"count\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "COUNT success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success count CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 496 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"count\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "COUNT error requests",
     "type": "timeseries",
     "description": "Total count of error count requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 496 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"count\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "COUNT error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error count CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 496 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"count\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "GET success requests",
     "type": "timeseries",
     "description": "Total count of success get requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 504 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"get\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "GET success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success get CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 504 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"get\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "GET error requests",
     "type": "timeseries",
     "description": "Total count of error get requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 504 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"get\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "GET error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error get CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 504 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"get\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "BORDERS success requests",
     "type": "timeseries",
     "description": "Total count of success MIN and MAX requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 512 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"borders\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "BORDERS success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success MIN and MAX CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 512 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"borders\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "BORDERS error requests",
     "type": "timeseries",
     "description": "Total count of error MIN and MAX requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 512 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"borders\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "BORDERS error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error MIN and MAX CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 512 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"borders\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "LEN success requests",
     "type": "timeseries",
     "description": "Total count of success len requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 520 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"len\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "LEN success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success len CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 520 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"len\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "LEN error requests",
     "type": "timeseries",
     "description": "Total count of error len requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 520 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"len\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "LEN error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error len CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 520 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"len\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "TRUNCATE success requests",
     "type": "timeseries",
     "description": "Total count of success truncate requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 528 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"truncate\",status=\"ok\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "TRUNCATE success requests latency",
     "type": "timeseries",
     "description": "99th percentile of success truncate CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 528 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"truncate\",quantile=\"0.99\",status=\"ok\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "TRUNCATE error requests",
     "type": "timeseries",
     "description": "Total count of error truncate requests to cluster spaces with CRUD module.\nGraph shows average requests per second.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable statistics with `crud.cfg{stats = true, stats_driver = 'metrics'}`\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 528 },
     "targets": [
      {
       "expr": "rate(tnt_crud_stats_count{alias=~\"$alias\",job=~\"$job\",operation=\"truncate\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    },
    {
     "title": "TRUNCATE error requests latency",
     "type": "timeseries",
     "description": "99th percentile of error truncate CRUD module requests latency with aging.\n\nCRUD 0.11.0 or newer is required to use statistics.\nEnable quantiles with `crud.cfg{stats = true, stats_driver = 'metrics', stats_quantiles = true}`.\nIf `No data` displayed yet data expected, try to calibrate tolerated error with\n`crud.cfg{stats_quantile_tolerated_error=1e-4}`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 528 },
     "targets": [
      {
       "expr": "tnt_crud_stats{alias=~\"$alias\",job=~\"$job\",operation=\"truncate\",quantile=\"0.99\",status=\"error\"}",
       "legendFormat": "{{alias}} — {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "expirationd module statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tuples checked",
     "type": "timeseries",
     "description": "A number of task tuples checked for expiration (expired + skipped).\nGraph shows mean tuples per second.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 537 },
     "targets": [
      {
       "expr": "rate(expirationd_checked_count{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{name}} — {{alias}}"
      }
     ]
    },
    {
     "title": "Tuples expired",
     "type": "timeseries",
     "description": "A number of task expired tuples.\nGraph shows mean tuples per second.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 537 },
     "targets": [
      {
       "expr": "rate(expirationd_expired_count{alias=~\"$alias\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{name}} — {{alias}}"
      }
     ]
    },
    {
     "title": "Restart count",
     "type": "timeseries",
     "description": "A number of task restarts since start.\nFrom the start is equal to 1.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 545 },
     "targets": [
      {
       "expr": "expirationd_restarts{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{name}} — {{alias}}"
      }
     ]
    },
    {
     "title": "Operation time",
     "type": "timeseries",
     "description": "A task's operation time.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 545 },
     "targets": [
      {
       "expr": "expirationd_working_time{alias=~\"$alias\",job=~\"$job\"}",
       "legendFormat": "{{name}} — {{alias}}"
      }
     ]
    }
   ]
  }
 ]
}