services:
  zookeeper-server:
    container_name: zookeeper-server
    hostname: zookeeper-server
    image: bitnami/zookeeper:3.9.3-debian-12-r0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
      - "2888:2888"
      - "8080:8080"
    networks:
      - cache

  kafka-broker:
    container_name: kafka-broker
    hostname: kafka-broker
    image: bitnami/kafka:3.8.1-debian-12-r0
    ports:
      - "29092:29092"
      - "9092:9092"
    depends_on:
      - zookeeper-server
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://:9092,EXTERNAL://127.0.0.1:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

    networks:
      - cache

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.55.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/configs:/etc/prometheus/configs:ro
    networks:
      - cache

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:11.3.0-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:rw
    networks:
      - cache

networks:
  cache:
    external: true